version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: tcmytt/chatapp-backend:1.0
    container_name: chat_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"

  frontend:
    image: tcmytt/chatapp-frontend:1.0
    container_name: chat_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NEXT_PUBLIC_WS_URL: ws://localhost:8080/chat
    ports:
      - "3000:3000"

volumes:
  postgres_data:
